export const INPUT_CHANGE = 'INPUT_CHANGE'

export const FETCH_GIF_REQUEST = 'FETCH_GIF_REQUEST'
export const FETCH_GIF_FAILURE = 'FETCH_GIF_FAILURE'
export const FETCH_GIF_SUCCESS = 'FETCH_GIF_SUCCESS'
